### ISSUE TITLE
Can't get the example to run

### ISSUE THREAD

**Issue by rharper2** [schaloner/deadbolt-2-java-examples#6] opened 2016-04-09 09:40 UTC
I am using activator-1.3.9-minimal

Two issues, failed dependencies with deadbolt-java_2.11;2.5.0-SNAPSHOT. I fix this by removing the snapshot

If I remove the SNAPSHOT, then it will compile, but when I run it, it asks to apply evolutions, which I do  and then comes back with a [CompletionException: java.lang.RuntimeException: There is no HTTP Context available from here.]

I must admit I am at a bit of a loss.

**Comment by schaloner** [comment] 2016-04-11 10:21
It's caused by the template being rendered in another thread - previously this worked, so it appears to be a side-effect of changes in Play.  I'll update the templates to take a Http.Context.

**Comment by schaloner** [comment] 2016-04-11 11:38
I've temporarily patched the example to work - if you get the latest version, you shouldn't have a problem.  See https://github.com/schaloner/deadbolt-2-java-examples/blob/master/app/controllers/Application.java#L22 for the patch.

**Comment by rharper2** [comment] 2016-04-12 03:26
Hi,

Confirmed working.

Thanks so much.

Robin

**Comment by schaloner** [comment] 2016-04-12 06:52
It's related to this - https://github.com/playframework/playframework/pull/5993

**Comment by schaloner** [comment] 2016-04-12 07:39
Fixed in https://github.com/schaloner/deadbolt-2-java-examples/commit/c1243848119716069d2efa8ab3716fbde65d0d1c

**Closed by schaloner** 2016-04-12 07:39 UTC
